### PR TITLE
NavBar

### PR DESCRIPTION
**Pull request by PakizeBozkurt**
Created NavBar with CSS.
#3

### CODE REVIEW

**Review by JanefrancessC — COMMENTED** [review]
You have done a great job Pakize! However, I have not seen where the NavBar was exported to in the App.js file

You can also write in the README.md file on how to access your contribution for easy review.
Finally, our App.js file needs to be modified to eliminate the React logo and all.

Well done on your work

**Comment by kavitappatil** [comment]
Everything looks good to me, well done on your work...

**Comment by PakizeBozkurt** [comment]
> You have done a great job Pakize! However, I have not seen where the NavBar was exported to in the App.js file
> 
> You can also write in the README.md file on how to access your contribution for easy review. Finally, our App.js file needs to be modified to eliminate the React logo and all.
> 
> Well done on your work

Thank you so much for reminding me!
I sorted out the App.js file.
I am gonna add README.md file.
🦖

**Comment by PakizeBozkurt** [comment]
> Everything looks good to me, well done on your work...

Thak you so much Kavita! 😺

**Pull request merged**
